### ISSUE TITLE
Can't run manage.py create_linkedin_config 

### ISSUE THREAD

**Issue by tkeemon** [appsembler/appsembleredx#1]
./manage.py cms create_linkedin_config --settings=aws_appsembler
Throws an error: 
```
Couldn't enable a LinkedIn Add to Profile configuration
CommandError: Couldn't enable a LinkedIn Add to Profile configuration
```

I tracked it down to this line: 
```
>>> enable =  models.LinkedInAddToProfileConfiguration(company_identifier=company_id, license_id=license_id or "", enabled=True)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/models/base.py", line 480, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'license_id' is an invalid keyword argument for this function
```

https://trello.com/c/wwTbd7Ct/900-4-nyif-production-push-microsites-certificates-reports

**Comment by bryanlandia** [comment]
I think this is fixed already.  Will verify.

**Comment by bryanlandia** [comment]
Yes, fixed here https://github.com/appsembler/appsembleredx/commit/53b3f3dd8907ba7ea3c2f935bf0552437ea3f83b
